// Renders a batch of MCQ objects — { question, options[], correctAnswerIndex,
// explanation, sectionTitle } — as a styled PDF, one card per question, each
// card listing every option with the correct one highlighted (filled accent
// circle + checkmark + accent-colored bold text).
//
// This is the MCQ counterpart to lib/pdfGenerator.js's "design_1" / "M.E.M
// design" template — it deliberately does NOT require('./pdfGenerator'), on
// purpose: it's a standalone file, so the header/footer chrome (the two
// checkerboard bands, the "BY M.E.M" footer wordmark + page number) is
// copied here verbatim from pdfGenerator.js rather than imported, so this
// file can evolve its MCQ-specific card layout independently without
// touching (or depending on) the written-question design.
//
// Input shape (see the /json_mcq command in api/telegram-webhook.js, which
// is the only caller): the `questions` array from a "questions_*.json" file
// generated by the MCQ-extraction flow —
//   { question, options: string[], correctAnswerIndex, explanation, sectionTitle }
// meta: { colorKey, footerBrand } — colorKey is one of lib/pdfColors.js's
// PDF_COLOR_PRESETS keys or a custom hex (defaults to orange/coral).
//
// Arabic text (a question, an option, or an explanation typed/extracted in
// Arabic) is shaped + bidi-reordered via lib/textShaping.js before drawing —
// PDFKit itself has no Arabic contextual-shaping or bidi support. Unlike
// pdfGenerator.js's answer body, MCQ option/explanation text has no
// *highlighted*-term markup to preserve, so each wrapped line is shaped and
// drawn as a single run (right-aligned for Arabic, left-aligned otherwise)
// instead of the word/run-level bold-tracking pdfGenerator.js needs for
// free-text answers.
const PDFDocument = require('pdfkit');
const path = require('path');
const { isMostlyArabic, shapeArabicLine, wrapWordsByWidth } = require('./textShaping');
const { getColorTheme, DEFAULT_PDF_COLOR } = require('./pdfColors');

// --- Fonts (same families/files as pdfGenerator.js's design_1) -----------
const FONT_ARABIC_REGULAR_PATH = path.join(__dirname, '../assets/fonts/NotoNaskhArabic-Regular.ttf');
const FONT_ARABIC_BOLD_PATH = path.join(__dirname, '../assets/fonts/NotoNaskhArabic-Bold.ttf');
const FONT_ARABIC_REGULAR = 'NotoNaskh-Regular';
const FONT_ARABIC_BOLD = 'NotoNaskh-Bold';

const FONT_REGULAR_PATH = path.join(__dirname, '../assets/fonts/ComicNeue-Regular.ttf');
const FONT_BOLD_PATH = path.join(__dirname, '../assets/fonts/ComicNeue-Bold.ttf');
const FONT_REGULAR = 'ComicNeue-Regular';
const FONT_BOLD = 'ComicNeue-Bold';

const FONT_HEADING_PATH = path.join(__dirname, '../assets/fonts/Fredoka-Bold.ttf');
const FONT_HEADING = 'Fredoka-Bold';

// --- Layout constants ------------------------------------------------------
const PAGE_MARGIN = 36;
const CHECKER_SIZE = 28; // identical header/footer band sizing to design_1

// Header: two stacked checkerboard rows, no title/banner — copied verbatim
// from pdfGenerator.js's drawHeader.
const HEADER_H = CHECKER_SIZE * 2;
const PAGE_CONTENT_TOP = HEADER_H + 22;

// Footer: two plain checkerboard rows, "BY M.E.M" brand + page number sit
// inside the upper row — copied verbatim from pdfGenerator.js's drawFooter.
const FOOTER_CHECKER_H = CHECKER_SIZE * 2;
const FOOTER_TOP_PAD = 10;
const FOOTER_H = FOOTER_TOP_PAD + FOOTER_CHECKER_H;

const CARD_PADDING = 16;
const CARD_GAP = 16;
const BADGE_R = 15;
const BADGE_COL_W = 40;
const QUESTION_SIZE = 15;
const LINE_HEIGHT_Q = 19;
const OPTION_SIZE = 12.5;
const LINE_HEIGHT_OPT = 16;
const OPTION_ROW_GAP = 8; // vertical gap between option rows
const OPTION_MARKER_R = 10; // radius of the A/B/C.. letter circle
const OPTION_MARKER_GAP = 10; // gap between marker and option text
const EXPLANATION_SIZE = 10.5;
const LINE_HEIGHT_EXP = 14;

// ---------------------------------------------------------------------
// Small text-measuring/drawing helpers — generic wrap+shape, no
// *highlighted*-term markup (MCQ options/explanations don't carry any).
// ---------------------------------------------------------------------
function wrapPlain(doc, text, font, arabicFont, size, maxWidth) {
  const raw = String(text || '');
  const arabic = isMostlyArabic(raw);
  const words = raw.split(/\s+/).filter(Boolean);
  const lines = wrapWordsByWidth(doc, words, arabic ? arabicFont : font, size, maxWidth);
  const shapedLines = arabic ? lines.map((l) => shapeArabicLine(l)) : lines;
  return { arabic, lines: shapedLines, height: Math.max(shapedLines.length, 1) * (size >= OPTION_SIZE ? (size >= QUESTION_SIZE ? LINE_HEIGHT_Q : LINE_HEIGHT_OPT) : LINE_HEIGHT_EXP) };
}

function drawWrapped(doc, measured, x, y, width, font, arabicFont, size, lineHeight, color) {
  doc.font(measured.arabic ? arabicFont : font).fontSize(size).fillColor(color);
  measured.lines.forEach((line, i) => {
    const ly = y + i * lineHeight;
    if (measured.arabic) {
      const w = doc.widthOfString(line);
      doc.text(line, x + Math.max(0, width - w), ly, { lineBreak: false });
    } else {
      doc.text(line, x, ly, { lineBreak: false });
    }
  });
}

function measureQuestion(doc, question, width) {
  return wrapPlain(doc, question, FONT_BOLD, FONT_ARABIC_BOLD, QUESTION_SIZE, width);
}

function drawQuestion(doc, colors, measured, x, y, width) {
  drawWrapped(doc, measured, x, y, width, FONT_BOLD, FONT_ARABIC_BOLD, QUESTION_SIZE, LINE_HEIGHT_Q, colors.orangeDark);
}

// Small "o——◆——o" separator under the question — copied verbatim from
// pdfGenerator.js's drawDivider.
function drawDivider(doc, colors, x, y, width) {
  const midX = x + width / 2;
  doc.save();
  doc.strokeColor(colors.divider).lineWidth(1);
  doc.moveTo(x, y).lineTo(midX - 8, y).stroke();
  doc.moveTo(midX + 8, y).lineTo(x + width, y).stroke();
  doc.circle(x, y, 2).fill(colors.divider);
  doc.circle(x + width, y, 2).fill(colors.divider);
  doc.restore();
  doc.save();
  doc.rotate(45, { origin: [midX, y] });
  doc.rect(midX - 4, y - 4, 8, 8).fill(colors.orange);
  doc.restore();
}

// One option row = a lettered marker circle + wrapped option text. The
// correct option gets a tinted highlight box behind it, a filled/checked
// marker, and bold accent-colored text; every other option gets a plain
// outlined marker and plain body text.
function measureOption(doc, optionText, isCorrect, width) {
  const textX = OPTION_MARKER_R * 2 + OPTION_MARKER_GAP;
  const textWidth = Math.max(10, width - textX);
  const measured = wrapPlain(doc, optionText, FONT_REGULAR, FONT_ARABIC_REGULAR, OPTION_SIZE, textWidth);
  const font = isCorrect ? FONT_BOLD : FONT_REGULAR;
  const arabicFont = isCorrect ? FONT_ARABIC_BOLD : FONT_ARABIC_REGULAR;
  return { ...measured, font, arabicFont, textX, textWidth, height: Math.max(measured.height, OPTION_MARKER_R * 2) };
}

function drawOption(doc, colors, letter, measured, isCorrect, x, y, width) {
  if (isCorrect) {
    doc.save();
    doc.fillOpacity(0.14);
    doc.roundedRect(x - 6, y - 5, width + 12, measured.height + 10, 8).fill(colors.orange);
    doc.restore();
  }

  const markerCx = x + OPTION_MARKER_R;
  const markerCy = y + measured.height / 2;
  if (isCorrect) {
    doc.circle(markerCx, markerCy, OPTION_MARKER_R).fill(colors.orange);
    doc.font(FONT_BOLD).fontSize(11).fillColor(colors.white);
    doc.text('\u2713', markerCx - OPTION_MARKER_R, markerCy - 5.5, { width: OPTION_MARKER_R * 2, align: 'center' });
  } else {
    doc.circle(markerCx, markerCy, OPTION_MARKER_R).lineWidth(1).stroke(colors.border);
    doc.font(FONT_BOLD).fontSize(10).fillColor(colors.gray);
    doc.text(letter, markerCx - OPTION_MARKER_R, markerCy - 5, { width: OPTION_MARKER_R * 2, align: 'center' });
  }

  drawWrapped(
    doc,
    measured,
    x + measured.textX,
    y + (measured.height - measured.lines.length * LINE_HEIGHT_OPT) / 2,
    measured.textWidth,
    measured.font,
    measured.arabicFont,
    OPTION_SIZE,
    LINE_HEIGHT_OPT,
    isCorrect ? colors.orangeDark : colors.text
  );
}

function measureExplanation(doc, text, width) {
  if (!text) return null;
  const labelW = 0; // label is drawn on its own line, not inline
  const measured = wrapPlain(doc, text, FONT_REGULAR, FONT_ARABIC_REGULAR, EXPLANATION_SIZE, width);
  return { ...measured, height: EXPLANATION_SIZE + 4 + measured.height };
}

function drawExplanation(doc, colors, measured, x, y, width) {
  doc.font(FONT_BOLD).fontSize(EXPLANATION_SIZE).fillColor(colors.gray);
  doc.text('Explanation:', x, y, { lineBreak: false });
  drawWrapped(doc, measured, x, y + EXPLANATION_SIZE + 4, width, FONT_REGULAR, FONT_ARABIC_REGULAR, EXPLANATION_SIZE, LINE_HEIGHT_EXP, colors.gray);
}

// Section banner — a solid accent banner drawn once, right before the
// first card of a new sectionTitle. Same visual language as
// pdfGenerator.js's chapter banner (drawChapterHeader), copied+simplified
// (no forced page-break — MCQ batches are usually short enough that
// forcing a fresh page per section would waste space).
const SECTION_SIZE = 14;
const SECTION_LINE_H = 18;
const SECTION_PAD_Y = 10;
const SECTION_PAD_X = 16;
const SECTION_GAP = 14;

function measureSection(doc, text, width) {
  const maxTextW = Math.max(10, width - SECTION_PAD_X * 2);
  const measured = wrapPlain(doc, text, FONT_BOLD, FONT_ARABIC_BOLD, SECTION_SIZE, maxTextW);
  const textHeight = Math.max(measured.lines.length, 1) * SECTION_LINE_H;
  return { ...measured, textHeight, height: textHeight + SECTION_PAD_Y * 2 };
}

function drawSection(doc, colors, measured, x, y, width) {
  doc.roundedRect(x, y, width, measured.height, 8).fill(colors.orange);
  const textStartY = y + (measured.height - measured.textHeight) / 2;
  drawWrapped(
    doc,
    measured,
    x + SECTION_PAD_X,
    textStartY,
    width - SECTION_PAD_X * 2,
    FONT_BOLD,
    FONT_ARABIC_BOLD,
    SECTION_SIZE,
    SECTION_LINE_H,
    colors.white
  );
}

// --- Header/footer chrome — copied verbatim from lib/pdfGenerator.js -----
function drawCheckerStrip(doc, colors, x, y, width, squareSize, rowIndex = 0, gaps = []) {
  const cols = Math.ceil(width / squareSize);
  doc.save();
  for (let i = 0; i < cols; i++) {
    const sx = x + i * squareSize;
    const sx2 = sx + squareSize;
    const inGap = gaps.some((g) => sx < g.x2 && sx2 > g.x1);
    if (inGap) continue;
    doc.rect(sx, y, squareSize, squareSize).fill((i + rowIndex) % 2 === 0 ? colors.orange : colors.white);
  }
  doc.restore();
}

function drawHeader(doc, colors, pageWidth) {
  drawCheckerStrip(doc, colors, 0, 0, pageWidth, CHECKER_SIZE, 0);
  drawCheckerStrip(doc, colors, 0, CHECKER_SIZE, pageWidth, CHECKER_SIZE, 1);
}

const DEFAULT_FOOTER_BRAND = 'BY M.E.M';
const FOOTER_WATERMARK_SIZE = 30;
const FOOTER_PAGE_NUM_SIZE = 13;
const FOOTER_GAP_PAD = 6;
const FOOTER_BRAND_GAP_BOXES = 5;

function oddBoxCountFor(width, squareSize) {
  let n = 1;
  while (n * squareSize < width) n += 2;
  return n;
}

function gridGapCenteredAt(centerX, boxes, squareSize) {
  const startCol = Math.round(centerX / squareSize - boxes / 2);
  return { x1: startCol * squareSize, x2: (startCol + boxes) * squareSize };
}

function drawFooter(doc, colors, pageNum, pageWidth, pageHeight, brand) {
  const checkerY = pageHeight - FOOTER_CHECKER_H;
  const upperRowY = checkerY;

  const brandText = (brand || DEFAULT_FOOTER_BRAND).toUpperCase();
  doc.font(FONT_HEADING).fontSize(FOOTER_WATERMARK_SIZE);
  const brandW = doc.widthOfString(brandText);
  const brandGap = gridGapCenteredAt(pageWidth / 2, FOOTER_BRAND_GAP_BOXES, CHECKER_SIZE);
  const brandX = brandGap.x1 + ((brandGap.x2 - brandGap.x1) - brandW) / 2;

  const pageNumText = String(pageNum);
  doc.font(FONT_BOLD).fontSize(FOOTER_PAGE_NUM_SIZE);
  const numW = doc.widthOfString(pageNumText);
  const numBoxes = oddBoxCountFor(numW + FOOTER_GAP_PAD * 2, CHECKER_SIZE);
  const numGap = gridGapCenteredAt(pageWidth - PAGE_MARGIN - numW / 2, numBoxes, CHECKER_SIZE);
  const numX1 = numGap.x1 + ((numGap.x2 - numGap.x1) - numW) / 2;

  drawCheckerStrip(doc, colors, 0, checkerY, pageWidth, CHECKER_SIZE, 0, [brandGap, numGap]);
  drawCheckerStrip(doc, colors, 0, checkerY + CHECKER_SIZE, pageWidth, CHECKER_SIZE, 1);

  const brandY = upperRowY + (CHECKER_SIZE - FOOTER_WATERMARK_SIZE) / 2 - 6;
  doc.font(FONT_HEADING).fontSize(FOOTER_WATERMARK_SIZE);
  doc.fillColor(colors.orange).strokeColor(colors.orangeDark).lineWidth(0.5);
  doc.text(brandText, brandX, brandY, { lineBreak: false, characterSpacing: 1.5, fill: true, stroke: true });

  const numY = upperRowY + (CHECKER_SIZE - FOOTER_PAGE_NUM_SIZE) / 2;
  doc.font(FONT_BOLD).fontSize(FOOTER_PAGE_NUM_SIZE).fillColor(colors.orangeDark);
  doc.text(pageNumText, numX1, numY, { lineBreak: false });
}

// questions: [{ question, options: string[], correctAnswerIndex,
// explanation, sectionTitle }] — see the /json_mcq command in
// api/telegram-webhook.js for exactly what shape is passed in (mirrors the
// "questions_*.json" file schema).
// meta: { colorKey, footerBrand }
function generateMcqPdf(questions, meta = {}) {
  return new Promise((resolve, reject) => {
    try {
      const colors = getColorTheme(meta.colorKey || DEFAULT_PDF_COLOR);
      const doc = new PDFDocument({ size: 'A4', margin: 0, bufferPages: false });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.registerFont(FONT_ARABIC_REGULAR, FONT_ARABIC_REGULAR_PATH);
      doc.registerFont(FONT_ARABIC_BOLD, FONT_ARABIC_BOLD_PATH);
      doc.registerFont(FONT_REGULAR, FONT_REGULAR_PATH);
      doc.registerFont(FONT_BOLD, FONT_BOLD_PATH);
      doc.registerFont(FONT_HEADING, FONT_HEADING_PATH);

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const contentX = PAGE_MARGIN;
      const contentWidth = pageWidth - PAGE_MARGIN * 2;

      let pageNum = 1;
      let y;

      function startPage() {
        drawHeader(doc, colors, pageWidth);
        y = PAGE_CONTENT_TOP;
      }

      function ensureSpace(neededHeight) {
        if (y + neededHeight > pageHeight - FOOTER_H - 14) {
          drawFooter(doc, colors, pageNum, pageWidth, pageHeight, meta.footerBrand);
          doc.addPage();
          pageNum += 1;
          startPage();
        }
      }

      startPage();

      let lastSection = null;

      questions.forEach((q, idx) => {
        if (q.sectionTitle && q.sectionTitle !== lastSection) {
          const secMeasured = measureSection(doc, q.sectionTitle, contentWidth);
          ensureSpace(secMeasured.height + SECTION_GAP);
          drawSection(doc, colors, secMeasured, contentX, y, contentWidth);
          y += secMeasured.height + SECTION_GAP;
          lastSection = q.sectionTitle;
        }

        const textColX = contentX + CARD_PADDING + BADGE_COL_W;
        const textColWidth = contentWidth - CARD_PADDING * 2 - BADGE_COL_W;
        const optionsWidth = contentWidth - CARD_PADDING * 2;

        const qMeasured = measureQuestion(doc, `Q${idx + 1}: ${q.question}`, textColWidth);
        const options = Array.isArray(q.options) ? q.options : [];
        const optMeasured = options.map((opt, i) => measureOption(doc, opt, i === q.correctAnswerIndex, optionsWidth));
        const optionsHeight =
          optMeasured.reduce((sum, o) => sum + o.height, 0) + OPTION_ROW_GAP * Math.max(0, optMeasured.length - 1);
        const expMeasured = measureExplanation(doc, q.explanation, optionsWidth);

        const innerHeight =
          qMeasured.height +
          10 + // divider gap
          12 + // gap before options
          optionsHeight +
          (expMeasured ? 12 + expMeasured.height : 0);
        const cardHeight = innerHeight + CARD_PADDING * 2 + 6;

        ensureSpace(cardHeight + CARD_GAP);

        const cardY = y;
        doc.roundedRect(contentX, cardY, contentWidth, cardHeight, 10).fillAndStroke(colors.cream, colors.border);

        const badgeCx = contentX + CARD_PADDING + BADGE_R;
        const badgeCy = cardY + CARD_PADDING + BADGE_R - 2;
        doc.circle(badgeCx, badgeCy, BADGE_R).fill(colors.orange);
        doc.font(FONT_BOLD).fontSize(12).fillColor(colors.white);
        doc.text(String(idx + 1), badgeCx - BADGE_R, badgeCy - 6, { width: BADGE_R * 2, align: 'center' });

        let curY = cardY + CARD_PADDING;
        drawQuestion(doc, colors, qMeasured, textColX, curY, textColWidth);
        curY += qMeasured.height + 8;

        drawDivider(doc, colors, textColX, curY, textColWidth);
        curY += 12;

        optMeasured.forEach((om, i) => {
          const letter = String.fromCharCode(65 + i);
          drawOption(doc, colors, letter, om, i === q.correctAnswerIndex, contentX + CARD_PADDING, curY, optionsWidth);
          curY += om.height + OPTION_ROW_GAP;
        });
        if (optMeasured.length > 0) curY -= OPTION_ROW_GAP;

        if (expMeasured) {
          curY += 12;
          drawExplanation(doc, colors, expMeasured, contentX + CARD_PADDING, curY, optionsWidth);
        }

        y = cardY + cardHeight + CARD_GAP;
      });

      drawFooter(doc, colors, pageNum, pageWidth, pageHeight, meta.footerBrand);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateMcqPdf };
